services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./rds-combined-ca-bundle.pem:/home/node/rds-combined-ca-bundle.pem:ro
    networks:
      - n8n-net

volumes:
  n8n_data:

networks:
  n8n-net:
    driver: bridge
