name: Deploy to OCI VM

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'yes' to confirm deployment to OCI"
        required: true
        default: "no"

jobs:
  deploy:
    if: ${{ github.event.inputs.confirm == 'yes' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to OCI
        run: |
          ssh ${{ secrets.OCI_USER }}@${{ secrets.OCI_HOST }} "
            cd ~/n8n || git clone https://github.com/yashguptadeveloper/n8n ~/n8n;
            cd ~/n8n &&
            git pull &&
            [ -f docker-compose.yml ] && docker compose down && docker compose up -d
          "
